#!/bin/bash

# Wrapper to runai from anywhere on command line
#python /Users/david/agents/main.py "$@"

# Function to check if a command exists
command_exists () {
    type "$1" &> /dev/null ;
}

# Check if python3 is available, else fall back to python
if command_exists python ; then
    PYTHON_CMD=python
elif command_exists python3 ; then
    PYTHON_CMD=python3
else
    echo "Python is not installed"
    exit 1
fi

# Get the directory of the current script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Run the Python script with arguments
$PYTHON_CMD "$SCRIPT_DIR/main.py" "$@"
# old hardcoded .. enable next line rather if you realy need to hardcode for some reason:
#$PYTHON_CMD /c/agents/main.py "$@"
